apiVersion: v1
metadata:
  name: my-pod-reading-secret
kind: Pod
spec:
  containers:
    - name: my-pod-reading-secret
      image: dev02
      imagePullPolicy: Never
      ports:
            - containerPort: 80
              protocol: TCP
      env:
        - name: mycred
          valueFrom:
              secretKeyRef:
                name: my-cred-secret
                key: user
