apiVersion: v1
metadata:
  name: 2-pod
kind: Pod
spec:
  volumes:
    - name: my-cred-secret
      secret:
          secretName: my-cred-secret
  containers:
    - name: 2-pod-container
      image: dev02
      imagePullPolicy: Never
      ports:
            - containerPort: 80
              protocol: TCP
      volumeMounts:
      - name: my-cred-secret
        mountPath: /deviator/my-data
      